# This is a basic workflow to help you get started with Actions

name: CI-TEST

# Event : Which trigers this work flow, Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image : postgres 
        env : 
          POSTGRES_USER : root 
          POSTGRES_PASSWORD : secret 
          POSTGRES_DB : banking 
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : Set up go 1.x 
        uses: actions/setup-go@v2 
        with: 
          go-version: ^1.15 
        id: go

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name : Checkout code into the Go Module Directory 
        uses: actions/checkout@v2 
      
      - name : Run Migrations 
        run: make migrateup

      - name : Build 
        run : go build -v .
      
      - name : Test 
        run : make test
